repoURL: "https://github.com/eklovya-sharma-gruve/openshift-cluster-setup.git"
applications:
  - application_name: application-demo
    namespace: demo-app
    project_name: application-config
    path: dev/gitops-operator-install-chart
  - application_name: local-storage-application
    namespace: openshift-local-storage
    project_name: gitops-cluster-config
    path: dev/gitops-operator-install-chart
  - application_name: odf-application
    namespace: openshift-storage
    project_name: gitops-cluster-config
    path: dev/gitops-operator-install-chart
app_group_param:
  gitops-cluster-config:
    project_name: gitops-cluster-config
    namespace:
      - openshift-local-storage
      - openshift-storage
      - openshift-logging
      - openshift-operators-redhat
    apiObject:
      - rg_name: operators.coreos.com
        rg_kind: OperatorGroup
      - rg_name: operators.coreos.com
        rg_kind: Subscription
      - rg_name: local.storage.openshift.io
        rg_kind: LocalVolume
      - rg_name: ocs.openshift.io
        rg_kind: StorageCluster
      - rg_name: objectbucket.io
        rg_kind: ObjectBucketClaim
      - rg_name: loki.grafana.com
        rg_kind: LokiStack
  application-config:
    project_name: gitops-cluster-config
    namespace:
      - demo-app
    apiObject:
      - rg_name: apps
        rg_kind: Deployment

