{{- range $app_group_key, $instances := .Values.app_group_param }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $app_group_key }}
  namespace: openshift-gitops
spec:
  sourceRepos:
    - {{ $.Values.repoURL | quote }}
  destinations:
    {{- range $instances.namespace }}
    - namespace: {{ . }}
      server: https://kubernetes.default.svc
    {{- end }}
  clusterResourceWhitelist:
    {{- range $instances.cs_apiObject }}
    - group: {{ .rg_name | quote }}
      kind: {{ .rg_kind }}
    {{- end }}
  namespaceResourceWhitelist:
    {{- range $instances.ns_apiObject }}
    - group: {{ .rg_name }}
      kind: {{ .rg_kind }}
    {{- end }}
---
{{- end }}
