{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .application_name }}
  namespace: openshift-gitops
spec:
  project: {{ .project_name }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace | quote }}
  revisionHistoryLimit: 10
  source:
    repoURL: {{ $.Values.repoURL | quote }}
    targetRevision: HEAD
    path: {{ .path }}
  syncPolicy:
    retry:
      backoff:
        factor: 5
        maxDuration: "100s"
        duration: "30s"
      limit: 3
---
{{- end }}